[WIP] Create json output option
open-io/gridinit pull request #25
Opened 2018-06-08 09:33 UTC by acornard

Add option to get json output.
Relates to #24

2018-06-08 09:41 UTC, vincent-legoll requested changes
But when you'll add YAML output, you will be allowed to let those trailing commas appear in output... ;-)

You may want to add some tests for your new-style output

2018-06-08 09:41 UTC, vincent-legoll commented on main/gridinit_cmd.c
> +	fprintf(stdout, "%s\"error\": \"%s\",\n", tab, error);
Are you sure JSON accepts trailing commas ?
```
vince@envy:~$ echo '[1,2,3]'|jsonlint-php 
Valid JSON
vince@envy:~$ echo '[1,2,3,]'|jsonlint-php 
Parse error on line 1:
[1,2,3,]
------^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' - It appears you have an extra trailing comma
```

2018-06-08 09:41 UTC, vincent-legoll commented on main/gridinit_cmd.c
> +			if (!first)
same as above comment, in addition your first looks like a boolean...

2018-06-22 12:26 UTC, acornard commented
Feature add on PR #34

2018-06-22 12:26 UTC, closed without merging